import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from 'sonner';
import { FaCheckCircle, FaTimesCircle } from 'react-icons/fa';


export const metadata: Metadata = {
  title: "Swap Goods and Services with Confidence",
  description: "Generated by create next app",
};
import {Providers} from "./providers";
import { ClerkProvider } from '@clerk/nextjs'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const customToastOptions = {
    style: {
      background: '#FD4677',
      color: '#fff',
    },
    success: {
      icon: <FaCheckCircle color="#4CAF50" />, // Green color for success
    },
    error: {
      icon: <FaTimesCircle color="#F44336" />, // Red color for error
    },
  };
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <Providers>
        {/* <Header/> */}
        {children}
        <Toaster position="top-center" theme="light" toastOptions={customToastOptions}/>
    </Providers>
        </body>
    </html>
    </ClerkProvider>
  );
}
