import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "sonner";
import { FaCheckCircle, FaTimesCircle } from "react-icons/fa";

export const metadata: Metadata = {
  title: "Swap Goods and Services with Confidence",
  description: "Generated by create next app",
};
import { Providers } from "./providers";
import { ClerkProvider } from "@clerk/nextjs";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const customToastOptions = {
    style: {
      background: "#FD4677",
      color: "#fff",
    },
    success: {
      icon: <FaCheckCircle color="#4CAF50" />, // Green color for success
    },
    error: {
      icon: <FaTimesCircle color="#F44336" />, // Red color for error
    },
  };
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <Script
            id="gtm-script"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-K4V6CTJS');`,
            }}
          />
        </head>
        <body className={inter.className}>
          <noscript>
            <iframe
              src="https://www.googletagmanager.com/ns.html?id=GTM-K4V6CTJS"
              height="0"
              width="0"
              style={{ display: "none", visibility: "hidden" }}
            />
          </noscript>
          <Providers>
            {children}
            <Toaster
              position="top-center"
              theme="light"
              toastOptions={customToastOptions}
            />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
