import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Swap Goods and Services with Confidence",
  description: "Generated by create next app",
};
import {Providers} from "./providers";
import { ClerkProvider } from '@clerk/nextjs'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <Providers>
        {/* <Header/> */}
        {children}
    </Providers>
        </body>
    </html>
    </ClerkProvider>
  );
}
